/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author arian
 */
public class Content_p4 extends javax.swing.JFrame {

    /**
     * Creates new form Content_p3
     */
    public Content_p4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaNum1 = new javax.swing.JTextArea();
        pnlBackground = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnMenu = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnLeft = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taxDefinition = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGenral = new javax.swing.JTextArea();
        lblTitle2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaDefinition2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaGeneral2 = new javax.swing.JTextArea();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaNum1.setEditable(false);
        txaNum1.setBackground(new java.awt.Color(92, 219, 149));
        txaNum1.setColumns(20);
        txaNum1.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaNum1.setForeground(new java.awt.Color(237, 245, 225));
        txaNum1.setLineWrap(true);
        txaNum1.setRows(5);
        txaNum1.setText("Example 1 :\nDetermine if 168 is divisible by 2, 3, or 5.\n\nlet's take a closer look at 168:\n\nThe last digit is 8, so 168 is divisible by 2.\nThe sum of the digits is 1+6+8=15, which is divisible by 3 so 168 is divisible by 3.\nThe last digit is not 0 or 5 so 156 is not divisible by 5.\nTherefore, 156 is divisible by 2 and 3 but not by 5.\n");
        txaNum1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaNum1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Tutor");

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));

        btnRight.setBackground(new java.awt.Color(92, 219, 149));
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(237, 245, 225));
        btnMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Introduction", "Divisibility", "Factor Pairs", "Prime and Composite Numbers", "Continued", "Prime Factorazation", "WRAP UP!" }));
        btnMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                btnMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_2.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("Prime Numbers");

        btnLeft.setBackground(new java.awt.Color(92, 219, 149));
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taxDefinition.setEditable(false);
        taxDefinition.setBackground(new java.awt.Color(92, 219, 149));
        taxDefinition.setColumns(20);
        taxDefinition.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        taxDefinition.setForeground(new java.awt.Color(55, 150, 131));
        taxDefinition.setLineWrap(true);
        taxDefinition.setRows(5);
        taxDefinition.setText("Definition: \nA prime number is a positive integer greater than 1 whose only divisors are 1 and itself.  A prime number has exactly two factors: 1 and itself.");
        taxDefinition.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taxDefinition);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGenral.setEditable(false);
        txaGenral.setBackground(new java.awt.Color(92, 219, 149));
        txaGenral.setColumns(20);
        txaGenral.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGenral.setForeground(new java.awt.Color(237, 245, 225));
        txaGenral.setLineWrap(true);
        txaGenral.setRows(5);
        txaGenral.setText("For instance, the only factor pair of 13 is 1×13.\nTherefore, 13 has just two factors: 1 and 13, so 13 is a prime number.\n\nThe prime numbers less than 40 are :\n2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37");
        txaGenral.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaGenral);

        lblTitle2.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle2.setText("cOMPOSITE nUMBERS");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDefinition2.setEditable(false);
        txaDefinition2.setBackground(new java.awt.Color(92, 219, 149));
        txaDefinition2.setColumns(20);
        txaDefinition2.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaDefinition2.setForeground(new java.awt.Color(55, 150, 131));
        txaDefinition2.setLineWrap(true);
        txaDefinition2.setRows(5);
        txaDefinition2.setText("Definition: \nA composite number is a positive integer that can be divided evenly by at least one positive integer other than 1 and itself. A composite number has more than two positive factors.");
        txaDefinition2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txaDefinition2);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral2.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral2.setColumns(20);
        txaGeneral2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txaGeneral2.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral2.setRows(5);
        txaGeneral2.setText("Let's look at 6. The number 6 can be written with factor pairs 1×6 or 2×3.\n\nFactors of 6 are 1, 2, 3, and 6.\n\nSince there are more than two factors, 6 is a composite number.\n\n");
        jScrollPane5.setViewportView(txaGeneral2);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRight)
                        .addGap(56, 56, 56)))
                .addComponent(icon)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(18, 18, 18)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLeft)
                                    .addComponent(btnRight)))
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // a button that brings up the next page
        new Content_p5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_btnMenuPopupMenuWillBecomeInvisible
        comboselect(); //applying the created method to the menue
    }//GEN-LAST:event_btnMenuPopupMenuWillBecomeInvisible

    // Creting the conditions for menu buttons to open different forms
    public void comboselect(){
        int intPageNum = btnMenu.getSelectedIndex();
        if (intPageNum == 0)
        {
            new Main_menu().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 2)
        {
            new Content_p2().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 3)
        {
            new Content_p3().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 1)
        {
            new Content_p1().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 5)
        {
            new Content_p5().setVisible(true);
            this.setVisible(false);
        }
                if (intPageNum == 6)
        {
            new Content_p7().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 7)
        {
            new Wrap_Up().setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // a button that brings up the previous page
        new Content_p3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content_p3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JComboBox<String> btnMenu;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea taxDefinition;
    private javax.swing.JTextArea txaDefinition2;
    private javax.swing.JTextArea txaGeneral2;
    private javax.swing.JTextArea txaGenral;
    private javax.swing.JTextArea txaNum1;
    // End of variables declaration//GEN-END:variables
}
