/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author arian
 */
public class Content_p7 extends javax.swing.JFrame {

    /**
     * Creates new form Content_p3
     */
    public Content_p7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaNum1 = new javax.swing.JTextArea();
        pnlBackground = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnMenu = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnLeft = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDefinition = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaSolution = new javax.swing.JTextArea();
        lblTree = new javax.swing.JLabel();
        btnMoreExamples = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaNum1.setEditable(false);
        txaNum1.setBackground(new java.awt.Color(92, 219, 149));
        txaNum1.setColumns(20);
        txaNum1.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaNum1.setForeground(new java.awt.Color(237, 245, 225));
        txaNum1.setLineWrap(true);
        txaNum1.setRows(5);
        txaNum1.setText("Example 1 :\nDetermine if 168 is divisible by 2, 3, or 5.\n\nlet's take a closer look at 168:\n\nThe last digit is 8, so 168 is divisible by 2.\nThe sum of the digits is 1+6+8=15, which is divisible by 3 so 168 is divisible by 3.\nThe last digit is not 0 or 5 so 156 is not divisible by 5.\nTherefore, 156 is divisible by 2 and 3 but not by 5.\n");
        txaNum1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaNum1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Tutor");

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));

        btnRight.setBackground(new java.awt.Color(92, 219, 149));
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(237, 245, 225));
        btnMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Introduction", "Divisibility", "Factor Pairs", "Prime and Composite Numbers", "Continued", "Prime Factorazation", "WRAP UP!" }));
        btnMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                btnMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_3.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("Prime Factorization");

        btnLeft.setBackground(new java.awt.Color(92, 219, 149));
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDefinition.setEditable(false);
        txaDefinition.setBackground(new java.awt.Color(92, 219, 149));
        txaDefinition.setColumns(20);
        txaDefinition.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaDefinition.setForeground(new java.awt.Color(55, 150, 131));
        txaDefinition.setLineWrap(true);
        txaDefinition.setRows(5);
        txaDefinition.setText("Definition: \nWe will now look at writing composite numbers as a product of primes.\n\nJust as mosaics are composed of a bunch of small tiles, composite numbers are composed of prime numbers that have been multiplied together. These small tiles are the building blocks for mosaics, and prime numbers are the building blocks for composite numbers.\n\nOne of the tools that will help us to factor a composite completely is a factor tree.\n\nHere is one possible factor tree for the number 20.");
        txaDefinition.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaDefinition);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaSolution.setBackground(new java.awt.Color(92, 219, 149));
        txaSolution.setColumns(20);
        txaSolution.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txaSolution.setForeground(new java.awt.Color(237, 245, 225));
        txaSolution.setRows(5);
        txaSolution.setText("Notice that the first level of this tree contains the factor pair 4×5.\n\nSince 5 is prime, we stop there.\n\nBut 4 can be written as 2×2 in another level of the tree.\n\n2 is prime, so we stop.");
        jScrollPane5.setViewportView(txaSolution);

        lblTree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prime_tree.png"))); // NOI18N

        btnMoreExamples.setText("More Examples");
        btnMoreExamples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreExamplesActionPerformed(evt);
            }
        });

        btnGoBack.setText("Try question from course beginning");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblTitle))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTree)
                .addGap(4, 4, 4)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnMoreExamples, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGoBack)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle))
                        .addGap(1, 1, 1)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoreExamples)
                            .addComponent(btnGoBack)))
                    .addComponent(lblTree))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // a button that brings up the next page
        new Wrap_Up().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_btnMenuPopupMenuWillBecomeInvisible
        comboselect(); //applying the created method to the menue
    }//GEN-LAST:event_btnMenuPopupMenuWillBecomeInvisible

    // Creting the conditions for menu buttons to open different forms
    public void comboselect(){
        int intPageNum = btnMenu.getSelectedIndex();
        if (intPageNum == 0)
        {
            new Main_menu().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 1)
        {
            new Content_p1().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 2)
        {
            new Content_p2().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 3)
        {
            new Content_p3().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 4)
        {
            new Content_p4().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 5)
        {
            new Content_p5().setVisible(true);
            this.setVisible(false);
        }
                if (intPageNum == 6)
        {
            new Content_p7().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 7)
        {
            new Wrap_Up().setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // a button that brings up the previous page
        new Content_p6().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnMoreExamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreExamplesActionPerformed
        new Examples().setVisible(true); //button to show more examples
    }//GEN-LAST:event_btnMoreExamplesActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
         // button to go back to question from page 1
        new Content_p1().setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content_p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content_p3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnLeft;
    private javax.swing.JComboBox<String> btnMenu;
    private javax.swing.JButton btnMoreExamples;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTree;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaDefinition;
    private javax.swing.JTextArea txaNum1;
    private javax.swing.JTextArea txaSolution;
    // End of variables declaration//GEN-END:variables
}
