/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author arian
 */
public class Content_p2 extends javax.swing.JFrame {

    /**
     * Creates new form Content_p2
     */
    public Content_p2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        btnMenu = new javax.swing.JComboBox<>();
        btnLeft = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btnRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGeneral = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGeneral2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGeneral3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Tutor");

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));
        pnlBackground.setPreferredSize(new java.awt.Dimension(659, 657));

        btnMenu.setBackground(new java.awt.Color(237, 245, 225));
        btnMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Introduction", "Divisibility", "Factor Pairs", "Prime and Composite Numbers", "Continued", "Prime Factorazation", "WRAP UP!" }));
        btnMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                btnMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnLeft.setBackground(new java.awt.Color(92, 219, 149));
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("divisibility");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_1.png"))); // NOI18N

        btnRight.setBackground(new java.awt.Color(92, 219, 149));
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral.setEditable(false);
        txaGeneral.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral.setColumns(20);
        txaGeneral.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral.setLineWrap(true);
        txaGeneral.setRows(5);
        txaGeneral.setText("Example 1 :\nDetermine if 168 is divisible by 2, 3, or 5.\n\nlet's take a closer look at 168:\n\nThe last digit is 8, so 168 is divisible by 2.\nThe sum of the digits is 1+6+8=15, which is divisible by 3 so 168 is divisible by 3.\nThe last digit is not 0 or 5 so 156 is not divisible by 5.\nTherefore, 156 is divisible by 2 and 3 but not by 5.\n");
        txaGeneral.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaGeneral);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral2.setEditable(false);
        txaGeneral2.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral2.setColumns(20);
        txaGeneral2.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral2.setForeground(new java.awt.Color(55, 150, 131));
        txaGeneral2.setRows(5);
        txaGeneral2.setText("Definition\nAny two positive integers that can be multiplied to obtain a given number are known as a\n factor pair. Each positive integer n has at least one factor pair, 1×n.\n\nRecall that a factor of a number is an integer that divides into that number leaving no \nremainder.  We might say that a factor of a number \"divides evenly\" into the number.");
        jScrollPane2.setViewportView(txaGeneral2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral3.setEditable(false);
        txaGeneral3.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral3.setColumns(20);
        txaGeneral3.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral3.setForeground(new java.awt.Color(240, 128, 128));
        txaGeneral3.setRows(5);
        txaGeneral3.setText("We will be looking for factor pairs and therefore, we will need to determine divisors of\n a number n. \nImportant Fact : When determining the smaller factor in each factor pair of a positive\ninteger n, it is only necessary to check integers less than or equal to  √ n .\n\nOnce we use factors after n−−√, we start to repeat values.\n\n");
        jScrollPane3.setViewportView(txaGeneral3);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addComponent(icon))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(17, 17, 17))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle))
                        .addGap(16, 16, 16)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_btnMenuPopupMenuWillBecomeInvisible
        comboselect(); // applying the created method to the menue
    }//GEN-LAST:event_btnMenuPopupMenuWillBecomeInvisible
    // Creting the conditions for menu buttons to open different forms
    public void comboselect(){
        int intPageNum = btnMenu.getSelectedIndex();
        if (intPageNum == 0)
        {
            new Main_menu().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 1)
        {
            new Content_p1().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 3)
        {
            new Content_p3().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 4)
        {
            new Content_p4().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 5)
        {
            new Content_p5().setVisible(true);
            this.setVisible(false);
        }
                if (intPageNum == 6)
        {
            new Content_p7().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 7)
        {
            new Wrap_Up().setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // a button that brings up the previous page
        new Content_p1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // a button that brings up the next page
        new Content_p3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content_p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content_p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content_p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content_p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content_p2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JComboBox<String> btnMenu;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaGeneral;
    private javax.swing.JTextArea txaGeneral2;
    private javax.swing.JTextArea txaGeneral3;
    // End of variables declaration//GEN-END:variables
}
