
import java.awt.Color;

/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author ahmad
 */
public class Content_p6 extends javax.swing.JFrame {

    /**
     * Creates new form Content_p6
     */
    

    
    public Content_p6() {
        initComponents();
        this.txaExample.setVisible(false); //disable example until user asks for
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaQestions = new javax.swing.JTextArea();
        chkboxPrime = new javax.swing.JCheckBox();
        chkboxComposite = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chkboxPrime1 = new javax.swing.JCheckBox();
        chkboxComposite1 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        chkboxPrime3 = new javax.swing.JCheckBox();
        chkboxComposite3 = new javax.swing.JCheckBox();
        chkboxPrime2 = new javax.swing.JCheckBox();
        chkboxComposite2 = new javax.swing.JCheckBox();
        btnCheck = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaExample = new javax.swing.JTextArea();
        btnExample = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Tutor");

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("Popup Quiz time!");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question_mark.png"))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaQestions.setBackground(new java.awt.Color(92, 219, 149));
        txaQestions.setColumns(20);
        txaQestions.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaQestions.setRows(5);
        txaQestions.setText("Determine if the following are prime or composite.\n\n1.105\n\n2.113\n\n3.31\n\n4.69");
        jScrollPane1.setViewportView(txaQestions);

        chkboxPrime.setText("Prime");
        chkboxPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPrimeActionPerformed(evt);
            }
        });

        chkboxComposite.setText("Composite");

        chkboxPrime1.setText("Prime");
        chkboxPrime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPrime1ActionPerformed(evt);
            }
        });

        chkboxComposite1.setText("Composite");

        chkboxPrime3.setText("Prime");
        chkboxPrime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPrime3ActionPerformed(evt);
            }
        });

        chkboxComposite3.setText("Composite");

        chkboxPrime2.setText("Prime");
        chkboxPrime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxPrime2ActionPerformed(evt);
            }
        });

        chkboxComposite2.setText("Composite");

        btnCheck.setText("Check Answers");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaExample.setEditable(false);
        txaExample.setBackground(new java.awt.Color(92, 219, 149));
        txaExample.setColumns(20);
        txaExample.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txaExample.setLineWrap(true);
        txaExample.setRows(5);
        txaExample.setText("To determine if 105 is prime or composite, check the integers up to 105−−−√≈10.2 to see if they form a factor pair.\nThe factor pairs of 105 are\n\n1×105\n3×35\n5×21\n7×15\nSince 105 has a factor pair other than 1×105, the integer 105 is composite.");
        txaExample.setWrapStyleWord(true);
        txaExample.setDisabledTextColor(new java.awt.Color(92, 219, 149));
        jScrollPane2.setViewportView(txaExample);

        btnExample.setText("Example");
        btnExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExampleActionPerformed(evt);
            }
        });

        btnRight.setBackground(new java.awt.Color(92, 219, 149));
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnLeft.setBackground(new java.awt.Color(92, 219, 149));
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left.png"))); // NOI18N
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                    .addComponent(chkboxPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(chkboxComposite, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2)
                                .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                    .addComponent(chkboxPrime1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(chkboxComposite1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator3)
                                .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                    .addComponent(chkboxPrime3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(chkboxComposite3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                    .addComponent(chkboxPrime2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(chkboxComposite2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCheck, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(99, 99, 99))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(lblTitle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnExample)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon)
                            .addComponent(lblTitle))
                        .addGap(47, 47, 47)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxPrime)
                            .addComponent(chkboxComposite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxPrime1)
                            .addComponent(chkboxComposite1))
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxPrime2)
                            .addComponent(chkboxComposite2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxPrime3)
                            .addComponent(chkboxComposite3))
                        .addGap(18, 18, 18)
                        .addComponent(btnCheck))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(btnExample)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        
    private void chkboxPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPrimeActionPerformed

    }//GEN-LAST:event_chkboxPrimeActionPerformed

    private void chkboxPrime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPrime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxPrime1ActionPerformed

    private void chkboxPrime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPrime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxPrime3ActionPerformed

    private void chkboxPrime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxPrime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxPrime2ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // if answer is correct it will be shown with green and if incorrect 
        // shown with red
        if (chkboxPrime.getSelectedObjects() == null)
        {
            chkboxComposite.setForeground(Color.green);
            chkboxPrime.setEnabled(false);
            chkboxComposite.setEnabled(false);
        }
        else if (chkboxPrime.getSelectedObjects() != null) 
        {
            chkboxPrime.setForeground(Color.red);
            chkboxPrime.setEnabled(false);
            chkboxComposite.setEnabled(false);
        }
        
        if (chkboxPrime1.getSelectedObjects() == null)
        {
            chkboxComposite1.setForeground(Color.red);
            chkboxPrime1.setEnabled(false);
            chkboxComposite1.setEnabled(false);
        }
        else if (chkboxPrime1.getSelectedObjects() != null)
        {
            chkboxPrime1.setForeground(Color.green);
            chkboxPrime1.setEnabled(false);
            chkboxComposite1.setEnabled(false);
        }
                
        if (chkboxPrime2.getSelectedObjects() == null)
        {
            chkboxComposite2.setForeground(Color.red);
            chkboxPrime2.setEnabled(false);
            chkboxComposite2.setEnabled(false);
        }
        else if (chkboxPrime2.getSelectedObjects() != null)
        {
            chkboxPrime2.setForeground(Color.green);
            chkboxPrime2.setEnabled(false);
            chkboxComposite2.setEnabled(false);
        }
        
        if (chkboxPrime3.getSelectedObjects() == null)
        {
            chkboxComposite3.setForeground(Color.green);
            chkboxPrime3.setEnabled(false);
            chkboxComposite3.setEnabled(false);
        }
        else if (chkboxPrime3.getSelectedObjects() != null)
        {
            chkboxPrime3.setForeground(Color.red);
            chkboxPrime3.setEnabled(false);
            chkboxComposite3.setEnabled(false);
        }
        btnCheck.setEnabled(false);

    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExampleActionPerformed
        txaExample.setVisible(true); // shows the example
    }//GEN-LAST:event_btnExampleActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // a button that brings up the next page
        new Content_p7().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // a button that brings up the previous page
        new Content_p5().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content_p6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content_p6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content_p6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content_p6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content_p6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnExample;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JCheckBox chkboxComposite;
    private javax.swing.JCheckBox chkboxComposite1;
    private javax.swing.JCheckBox chkboxComposite2;
    private javax.swing.JCheckBox chkboxComposite3;
    private javax.swing.JCheckBox chkboxPrime;
    private javax.swing.JCheckBox chkboxPrime1;
    private javax.swing.JCheckBox chkboxPrime2;
    private javax.swing.JCheckBox chkboxPrime3;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaExample;
    private javax.swing.JTextArea txaQestions;
    // End of variables declaration//GEN-END:variables
}
