
import java.awt.Color;

/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author arian
 */
public class Content_p1 extends javax.swing.JFrame {

    /**
     * Creates new form Content_p1
     */
    public Content_p1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btnMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGeneral = new javax.swing.JTextArea();
        pic1 = new javax.swing.JLabel();
        btnRight = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGeneral2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGeneral3 = new javax.swing.JTextArea();
        txtAnswer = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();

        setTitle("Math Tutor");

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("Introduction");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logic.png"))); // NOI18N

        btnMenu.setBackground(new java.awt.Color(237, 245, 225));
        btnMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Introduction", "Divisibility", "Factor Pairs", "Prime and Composite Numbers", "Continued", "Prime Factorazation", "WRAP UP!" }));
        btnMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                btnMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral.setEditable(false);
        txaGeneral.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral.setColumns(20);
        txaGeneral.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral.setRows(5);
        txaGeneral.setText("Some of the things surrounding us have been formed by taking simple things or building\n blocks and combining them together.\n\nWhen cooking, you may use more basic ingredients such as meats, vegetables, and\n spices that,when cooked together, create a delicious meal full of different flavors.");
        jScrollPane1.setViewportView(txaGeneral);

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ingridients.jpg"))); // NOI18N

        btnRight.setBackground(new java.awt.Color(92, 219, 149));
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral2.setEditable(false);
        txaGeneral2.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral2.setColumns(20);
        txaGeneral2.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral2.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral2.setRows(5);
        txaGeneral2.setText("In math, we often think numbers are independent of each other. However, numbers are \nalso made up of building blocks called prime numbers. In this lesson, we will look at \nprime and composite numbers.");
        jScrollPane2.setViewportView(txaGeneral2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral3.setEditable(false);
        txaGeneral3.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral3.setColumns(20);
        txaGeneral3.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        txaGeneral3.setForeground(new java.awt.Color(5, 56, 107));
        txaGeneral3.setRows(5);
        txaGeneral3.setText("Give it a try : \nDetermine the values of the integers x, y, and z such that 2^x + 3^y + 7^z = 42 336.\n(Input your answer as x,y,z for ex: 2,3,4)");
        jScrollPane3.setViewportView(txaGeneral3);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numbers.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(icon2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pic1)
                        .addGap(20, 20, 20))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(lblTitle)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))
                        .addComponent(icon)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCheck)
                .addGap(119, 119, 119))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1)
                    .addComponent(icon2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_btnMenuPopupMenuWillBecomeInvisible
        comboselect(); // applying the created method to the menue
    }//GEN-LAST:event_btnMenuPopupMenuWillBecomeInvisible
    
    // Creting the conditions for menu buttons to open different forms
    public void comboselect(){
        int intPageNum = btnMenu.getSelectedIndex();
        if (intPageNum == 0)
        {
            new Main_menu().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 2)
        {
            new Content_p2().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 3)
        {
            new Content_p3().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 4)
        {
            new Content_p4().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 5)
        {
            new Content_p5().setVisible(true);
            this.setVisible(false);
        }
                if (intPageNum == 6)
        {
            new Content_p7().setVisible(true);
            this.setVisible(false);
        }
        if (intPageNum == 7)
        {
            new Wrap_Up().setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        //Declaring Variable
        String strAnswer = txtAnswer.getText();
        
        /* Setting the if condition to change color base on the answer also 
        change button's text (there's a easter egg too!)
        */
        if (strAnswer.equals("5,3,2"))
        {
            this.txtAnswer.setForeground(Color.GREEN);
            this.btnCheck.setText("Correct");
        }
        if (strAnswer.equals("2,3,4"))
        {
            this.txtAnswer.setForeground(Color.ORANGE);
            this.btnCheck.setText("Not that simple");
        }
        else
        {
            this.txtAnswer.setForeground(Color.red);
            this.btnCheck.setText("Try again");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // a button that brings up the next page
        new Content_p2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Content_p1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JComboBox<String> btnMenu;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel pic1;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaGeneral;
    private javax.swing.JTextArea txaGeneral2;
    private javax.swing.JTextArea txaGeneral3;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
