/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author ahmad
 */
public class Examples2 extends javax.swing.JFrame {

    /**
     * Creates new form Examples
     */
    public Examples2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGeneral = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGeneral1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaGeneral3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaGeneral4 = new javax.swing.JTextArea();
        btnBackToMain = new javax.swing.JButton();

        pnlBackground.setBackground(new java.awt.Color(92, 219, 149));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral.setEditable(false);
        txaGeneral.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral.setColumns(20);
        txaGeneral.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txaGeneral.setLineWrap(true);
        txaGeneral.setRows(5);
        txaGeneral.setText("We know that the exponents of the prime factors of a perfect square must be even.\n\nFor N=3^3×5×k to be a perfect square, the exponent having a base of 3 and the exponent having a base of 5 must each be even.\n\nN includes 3^3, therefore k must include one factor of 3 so that N has a factor of 3^4.\n\nSimilarly, k must include one factor of 5.\n\nTherefore, k=3×5 or k=15.");
        txaGeneral.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaGeneral);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral1.setEditable(false);
        txaGeneral1.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral1.setColumns(20);
        txaGeneral1.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txaGeneral1.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral1.setLineWrap(true);
        txaGeneral1.setRows(5);
        txaGeneral1.setText("Determine the smallest value of the positive integer k so that N=33×5×k is a perfect square.");
        txaGeneral1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaGeneral1);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral3.setEditable(false);
        txaGeneral3.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral3.setColumns(20);
        txaGeneral3.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txaGeneral3.setForeground(new java.awt.Color(237, 245, 225));
        txaGeneral3.setLineWrap(true);
        txaGeneral3.setRows(5);
        txaGeneral3.setText("Determine the smallest value of the positive integer m so that N=2400m is a perfect square.");
        txaGeneral3.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txaGeneral3);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaGeneral4.setEditable(false);
        txaGeneral4.setBackground(new java.awt.Color(92, 219, 149));
        txaGeneral4.setColumns(20);
        txaGeneral4.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txaGeneral4.setLineWrap(true);
        txaGeneral4.setRows(5);
        txaGeneral4.setText("We know that the exponents of the prime factors of a perfect square must be even. In this example, we cannot see the prime factors of 2400. Begin by rewriting N using the prime factors of 2400:\n\n\t\tN=2^5×3×5^2×m\n\nFor N=2^5×3×5^2×m to be a perfect square, the exponents having bases of 2, 3 and 5 must be even. We are given 2^5, so m must include one factor of 2 so that N contains 2^6. It must also contain one factor of 3 so that N contains 3^2.\n\nTherefore, m=2×3 or m=6.");
        txaGeneral4.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txaGeneral4);

        btnBackToMain.setText("Back to main page");
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMain)
                .addGap(25, 25, 25))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackToMain)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed
        this.setVisible(false); // button to hide this page
    }//GEN-LAST:event_btnBackToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaGeneral;
    private javax.swing.JTextArea txaGeneral1;
    private javax.swing.JTextArea txaGeneral3;
    private javax.swing.JTextArea txaGeneral4;
    // End of variables declaration//GEN-END:variables
}
