
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;

/*
 * Developed by Arian Ahmadinejad
 * From Jul 12 to Jul 17 2020
 * Final Project : Math Tutor
 * Software made to help grade 9 students with learning prime functions
 */

/**
 *
 * @author ahmad
 */
public class quiz extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    
    ArrayList <String> qList = new ArrayList();
    ArrayList <String> aList = new ArrayList();
    int counter = 0;
    int Score = 0;
    Boolean bolPressed = false;
    public quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        txtInput = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(92, 219, 149));

        lblTitle.setFont(new java.awt.Font("Transformers Movie", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(5, 56, 107));
        lblTitle.setText("QUize TIme");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaOutput.setEditable(false);
        txaOutput.setColumns(20);
        txaOutput.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        txaOutput.setLineWrap(true);
        txaOutput.setRows(5);
        txaOutput.setText("Input your answers according to the following formats based on the question :\n1,2,3,4,....\ncomposite,prime,......\nyes,no");
        txaOutput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaOutput);

        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(240, 240, 240))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnStart)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Collections.addAll(qList, "1 - Determine if each number is prime or"
                                + " composite." + "\n" + "a. 37      b.81  "
                                + "     c.63        d. 101");
        Collections.addAll(qList, "2 - For each set of numbers, state whether "
                                + "they have a factor in common, other than  1."
                                + "\na. 11,13     b. 12,15    c. 12,25    "
                                + "d. 8,12,15");
        Collections.addAll(qList, "3 - Express 2880 as a product of its"
                                + " primes.\na. 2^2×5×101      b. 2^3*5^3*7      "
                                + "c. 2×3^2×5^2       d. 2^6×3^2×5");
        Collections.addAll(qList, "4 - Determine the smallest value of the "
                                + "positive integer k such that 80k is:"
                                + "\na. a perfect square    b. a perfect cube"
                                + "c. a perfect 4th power   d. a perfect 5th"
                                + " power");
        Collections.addAll(qList, "5 - 658 503 unit cubes are used to assemble a"
                                + " giant cube on display. If replicas of a "
                                + "famous smaller cube (made using 3×3×3 unit"
                                + " cubes) were used to assemble the giant cube,"
                                + " how many replicas are needed? \na. 17^3"
                                + "     b. 19^3     c. 29 ^ 3       d.23 ^ 3");
        
        Collections.addAll(aList,"prime,composite,composite,prime",
                                 "no,yes,no,no","d","5,100,125,1250","c");
     
        this.txaOutput.setText(qList.get(0));
        bolPressed = true;
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        counter ++;
        
        if (bolPressed == true)
        {
            if (counter == qList.size())
        {
            Color myGreen = new Color(92,219,149);
            this.txaOutput.setForeground(Color.red);
            this.txaOutput.setSize(344, 36);
            this.txaOutput.setBackground(myGreen);
            this.txaOutput.setAlignmentX(CENTER_ALIGNMENT);
            this.txaOutput.setText("Your score is " + Score + "/5");
            btnNext.setVisible(false);
            btnStart.setVisible(false);
            txtInput.setVisible(false);
        }
        else
        {
            this.txaOutput.setText(qList.get(counter));
            if ((txtInput.getText()).equals(aList.get(counter-1)))
            {
                Score ++;
            }
            else
            {
                ;
            }
        }   
        }
        else
        {
            txaOutput.setText("Please press the start button first.");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked

    }//GEN-LAST:event_btnNextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
